CREATE TABLE request (
    row_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ref_token   TEXT      NOT NULL,
    chat_ref    TEXT      NOT NULL,
    user_ref    TEXT      NOT NULL,
    short_id    TEXT      NOT NULL,
    state       TEXT      NOT NULL,
    created_at  TIMESTAMP NOT NULL,
    expires_at  TIMESTAMP NOT NULL,
    closed_at   TIMESTAMP,              -- set when the request leaves OPEN
    payload     BYTEA     NOT NULL
);
CREATE UNIQUE INDEX request_ref_token_idx ON request (ref_token);
CREATE INDEX request_chat_state_idx ON request (chat_ref, state);
CREATE INDEX request_user_idx ON request (user_ref);

CREATE TABLE chat_settings (
    chat_ref   TEXT PRIMARY KEY,
    payload    BYTEA NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE fx_rate (
    base       TEXT NOT NULL,
    quote      TEXT NOT NULL,
    rate       DECIMAL(30, 10) NOT NULL,
    fetched_at TIMESTAMP NOT NULL,
    PRIMARY KEY (base, quote)
);

CREATE TABLE sent_message (
    chat_ref   TEXT      NOT NULL,
    message_id BIGINT    NOT NULL,
    sent_at    TIMESTAMP NOT NULL,
    PRIMARY KEY (chat_ref, message_id)
);

CREATE TABLE sent_message_ref (
    chat_ref   TEXT   NOT NULL,
    message_id BIGINT NOT NULL,
    ref_token  TEXT   NOT NULL,
    user_ref   TEXT   NOT NULL
);
CREATE INDEX sent_message_ref_token_idx ON sent_message_ref (ref_token);
CREATE INDEX sent_message_ref_user_idx ON sent_message_ref (user_ref);

-- db-scheduler 16.x canonical schema. task_data stays empty by design (ADR: tasks
-- are parameterless so nothing sensitive lands in this unencrypted BYTEA).
CREATE TABLE scheduled_tasks (
    task_name            VARCHAR(255) NOT NULL,
    task_instance        VARCHAR(255) NOT NULL,
    task_data            BYTEA,
    execution_time       TIMESTAMP WITH TIME ZONE NOT NULL,
    picked               BOOLEAN NOT NULL,
    picked_by            VARCHAR(50),
    last_success         TIMESTAMP WITH TIME ZONE,
    last_failure         TIMESTAMP WITH TIME ZONE,
    consecutive_failures INT,
    last_heartbeat       TIMESTAMP WITH TIME ZONE,
    version              BIGINT NOT NULL,
    priority             SMALLINT,
    PRIMARY KEY (task_name, task_instance)
);
CREATE INDEX execution_time_idx ON scheduled_tasks (execution_time);
CREATE INDEX last_heartbeat_idx ON scheduled_tasks (last_heartbeat);
CREATE INDEX priority_execution_time_idx ON scheduled_tasks (priority DESC, execution_time ASC);
