package fxbot

import com.google.crypto.tink.InsecureSecretKeyAccess
import com.google.crypto.tink.KeyStatus
import com.google.crypto.tink.KeysetHandle
import com.google.crypto.tink.TinkJsonProtoKeysetFormat
import com.google.crypto.tink.aead.AeadConfig
import com.google.crypto.tink.aead.PredefinedAeadParameters
import com.google.crypto.tink.mac.HmacParameters
import com.google.crypto.tink.mac.MacConfig
import io.kotest.assertions.throwables.shouldThrow
import io.kotest.assertions.throwables.shouldThrowAny
import io.kotest.core.spec.style.StringSpec
import io.kotest.matchers.shouldBe
import io.kotest.matchers.shouldNotBe
import java.security.GeneralSecurityException

private fun serialize(handle: KeysetHandle): String =
    TinkJsonProtoKeysetFormat.serializeKeyset(handle, InsecureSecretKeyAccess.get())

/** AES-128-GCM, structurally valid for Tink but weaker than the mandated AES-256-GCM. */
private fun weakAeadKeyset(): String {
    AeadConfig.register()
    return serialize(KeysetHandle.generateNew(PredefinedAeadParameters.AES128_GCM))
}

/** HMAC-SHA1, structurally valid for Tink but not the mandated HMAC-SHA256. */
private fun weakMacParameters(): HmacParameters =
    HmacParameters.builder()
        .setKeySizeBytes(20)
        .setTagSizeBytes(20)
        .setHashType(HmacParameters.HashType.SHA1)
        .setVariant(HmacParameters.Variant.TINK)
        .build()

private fun weakMacKeyset(): String {
    MacConfig.register()
    return serialize(KeysetHandle.generateNew(weakMacParameters()))
}

class CryptoTest : StringSpec({
    val crypto = Crypto(KeysetGen.aead(), KeysetGen.mac())

    "round-trips a payload under its associated data" {
        val sealed = crypto.seal("""{"username":"alice"}""", "tok-1")
        crypto.open(sealed, "tok-1") shouldBe """{"username":"alice"}"""
    }
    "refuses to open under different associated data" {
        val sealed = crypto.seal("secret", "tok-1")
        shouldThrowAny { crypto.open(sealed, "tok-2") }
    }
    "refuses to open a tampered ciphertext" {
        val sealed = crypto.seal("secret", "tok-1")
        sealed[sealed.size - 1] = (sealed[sealed.size - 1] + 1).toByte()
        shouldThrowAny { crypto.open(sealed, "tok-1") }
    }
    "refuses to open under a different key" {
        val other = Crypto(KeysetGen.aead(), KeysetGen.mac())
        shouldThrowAny { other.open(crypto.seal("secret", "tok-1"), "tok-1") }
    }
    "encrypts the same plaintext to different ciphertexts" {
        crypto.seal("same", "tok-1") shouldNotBe crypto.seal("same", "tok-1")
    }
    "refs are deterministic and key-dependent" {
        crypto.ref("-1001") shouldBe crypto.ref("-1001")
        crypto.ref("-1001") shouldNotBe crypto.ref("-1002")
        Crypto(KeysetGen.aead(), KeysetGen.mac()).ref("-1001") shouldNotBe crypto.ref("-1001")
    }
    "a ref is a stable non-empty string" {
        // Columns are TEXT, so no width is asserted — Tink prepends a key-identity
        // prefix whose size is not ours to hard-code.
        crypto.ref("-1001").isNotEmpty() shouldBe true
        crypto.ref("-1001") shouldBe crypto.ref("-1001")
    }
    "ref tokens are 22 characters and unique" {
        val tokens = List(1000) { newRefToken() }
        tokens.toSet().size shouldBe 1000
        tokens.all { it.length == 22 } shouldBe true
    }
    "accepts keysets generated by KeysetGen.aead() and KeysetGen.mac()" {
        Crypto(KeysetGen.aead(), KeysetGen.mac())
    }
    "rejects an AES-128-GCM AEAD keyset" {
        shouldThrow<GeneralSecurityException> { Crypto(weakAeadKeyset(), KeysetGen.mac()) }
    }
    "rejects a non-SHA256 MAC keyset" {
        shouldThrow<GeneralSecurityException> { Crypto(KeysetGen.aead(), weakMacKeyset()) }
    }
    "rejects an AEAD keyset whose primary is AES-256-GCM but which also holds a weak enabled non-primary key" {
        AeadConfig.register()
        val mixed =
            KeysetHandle.newBuilder()
                .addEntry(
                    KeysetHandle.generateEntryFromParameters(PredefinedAeadParameters.AES256_GCM)
                        .withRandomId()
                        .makePrimary(),
                )
                .addEntry(
                    KeysetHandle.generateEntryFromParameters(PredefinedAeadParameters.AES128_GCM)
                        .withRandomId()
                        .setStatus(KeyStatus.ENABLED),
                )
                .build()
        shouldThrow<GeneralSecurityException> { Crypto(serialize(mixed), KeysetGen.mac()) }
    }
})
